// Writes a .env pointing at the local Supabase stack, so the dev server and the
// E2E suite talk to Docker instead of a hosted project.
//
// Keys are read from `supabase status` rather than hardcoded: the CLI's local
// credentials have changed format across versions (JWT anon keys, then
// sb_publishable_/sb_secret_), and a stale constant fails as a confusing auth
// error rather than an obvious one.
//
// Usage: node scripts/db-local.mjs [--print]
//   default   overwrite .env with local-stack settings (backs up an existing one)
//   --print   write nothing, just show what was detected
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = resolve(root, ".env");
const printOnly = process.argv.includes("--print");

let raw;
try {
  raw = execFileSync("npx", ["supabase", "status", "-o", "env"], {
    cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"],
  });
} catch (e) {
  console.error(
    "Could not read `supabase status`. Is the local stack running?\n" +
    "  npm run db:start\n\n" +
    (e.stderr || e.message || "")
  );
  process.exit(1);
}

// `-o env` emits KEY="value" lines.
const status = Object.fromEntries(
  raw.split("\n").filter((l) => l.includes("=")).map((l) => {
    const i = l.indexOf("=");
    return [l.slice(0, i).trim(), l.slice(i + 1).trim().replace(/^"|"$/g, "")];
  })
);

const apiUrl = status.API_URL;
// Newer CLIs expose publishable/secret; older ones only anon/service_role.
const publishable = status.PUBLISHABLE_KEY || status.ANON_KEY;
const secret = status.SECRET_KEY || status.SERVICE_ROLE_KEY;

if (!apiUrl || !publishable || !secret) {
  console.error("`supabase status` did not report the expected keys. Got:\n" + Object.keys(status).join(", "));
  process.exit(1);
}

console.log(`API URL:     ${apiUrl}`);
console.log(`publishable: ${publishable.slice(0, 12)}…`);
console.log(`secret:      ${secret.slice(0, 12)}…`);

if (printOnly) process.exit(0);

// Preserve AI keys from the existing .env — the local stack has no opinion on
// them and losing them silently breaks the Recommend tab.
const carried = {};
if (existsSync(envPath)) {
  for (const line of readFileSync(envPath, "utf8").split(/\r?\n/)) {
    const m = line.match(/^(ANTHROPIC_API_KEY|GEMINI_API_KEY|OWNER_EMAIL)=(.*)$/);
    if (m) carried[m[1]] = m[2];
  }
  copyFileSync(envPath, `${envPath}.hosted-backup`);
  console.log(`\nBacked up existing .env → .env.hosted-backup`);
}

writeFileSync(envPath, [
  "# Generated by scripts/db-local.mjs — points at the LOCAL Supabase stack.",
  "# Restore the hosted config from .env.hosted-backup.",
  `VITE_SUPABASE_URL=${apiUrl}`,
  `VITE_SUPABASE_PUBLISHABLE_KEY=${publishable}`,
  `SUPABASE_URL=${apiUrl}`,
  `SUPABASE_SECRET_KEY=${secret}`,
  ...Object.entries(carried).map(([k, v]) => `${k}=${v}`),
  "",
].join("\n"));

console.log("Wrote .env pointing at the local stack.");
